### ISSUE TITLE
google analytics page call

### ISSUE THREAD

**Issue by stevenmiller888** [segmentio/analytics.js-integrations#528]
@amillet89  When there is a hash in the pathname, for example, http://www.tuti.com/#/what-is-it/, the event fired off to GA  contains the path "/". But the customer wants the path to be /#/what-is-it/, and cannot override it since he is using angularitics. What are your thoughts on this?

![e1a76048-b109-11e4-8541-f0f470c80e33](https://cloud.githubusercontent.com/assets/7015626/6139535/c76d9e80-b141-11e4-884c-48fb05b71404.png)

**Comment by guillaumecabane** [comment]
+1 on that one

**Comment by f2prateek** [comment]
Seems like an important behaviour change, would mess with existing data (that ignore the `#`).

**Comment by ndhoule** [comment]
Not super familiar with Angularitics, but the issue here is that hash URLs are not "real" URLs—they're hashes that your app uses to navigate to a particular state. (This is just one of the many reasons hash/hashbang URLs are not great.) The ideal solution is to not use hash URLs and instead use Angular's HTML5 mode/change your server's route handling accordingly—but that's not always possible given that not every browser supports the history API.

Analytics.js will let you override the page URL, hash, etc. by simply specifying it in your page call's properties. Seems to me this is an issue in Angularitics; it should allow you to override those properties if need be, or provide a hash mode where it takes care of this issue for you.

I'm closing this for now, but if there's part of this issue I'm misunderstanding, feel free to reopen it over on https://github.com/segmentio/analytics.js, since this is more of an analytics.js core issue.
