### ISSUE TITLE
Conflict between Optimizely and Intercom integrations

### ISSUE THREAD

**Issue by hadees** [segmentio/analytics.js-integrations#617]
On our site we use both Optimizely and Intercom.  The problem we are having is that Optimizely calls `identify` as part of its [`initialize` method](https://github.com/segmentio/analytics.js-integrations/blob/master/lib/optimizely/index.js#L167).  This in turn causes Segment to identify all of our integrations including Intercom.  Intercom then [checks for a `user_id` or `email`](https://github.com/segmentio/analytics.js-integrations/blob/master/lib/intercom/index.js#L78-L80), which it finds because they are cached from a previous identify, and lets the Intercom identify go ahead.  However since Intercom is in secure mode the identify fails because it's missing the `user_hash`.

![screen shot 2015-05-11 at 4 28 46 pm](https://cloud.githubusercontent.com/assets/15341/7575951/e7bfd500-f7fe-11e4-9a0e-7aac99443920.png)

This issue is related to a pull request I made before #603.  I incorrectly assumed Intercom forces secure mode however I feel like a similar solution is required.  Intercom should not be identifying if secure mode is enabled and the `user_hash` is missing.  I've been talking back and forth on email with @eoin about this issue but in light of the connection to Optimizely I figured it made more sense to discuss this here.

**Comment by hadees** [comment]
@sperand-io let me know your thoughts on this, I'm not sure if there are guidelines but Optimizely or Intercom should probably change their integration.

**Comment by sperand-io** [comment]
@hadees ahh, thanks for the detailed report! indeed, we're in the midst of phasing out the option to automatically call `identify` from the Optimizely integration.

if you switch from this:

![](https://cloudup.com/cObDET_ZTnh+)

to this:

![](https://cloudup.com/cpkzYjpN4m9+)

you'll hit [this](https://github.com/segmentio/analytics.js-integrations/blob/master/lib/optimizely/index.js#L99-L120) code path instead of [this](https://github.com/segmentio/analytics.js-integrations/blob/master/lib/optimizely/index.js#L146-L168) one.

LMK if that would solve for your issue!

**Comment by ndhoule** [comment]
@hadees Looks like there's a fix for this (above), so I'm closing this—but please do open a new issue over on https://github.com/segment-integrations/analytics.js-integration-optimizely and link back to this one if @sperand-io's solution doesn't fix your issue.
